default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: x_tracker_development
  url: postgres://postgres@127.0.0.1:5432
  password: <%= ENV.fetch("X_TRACKER_DATABASE_PASSWORD", 'postgres') %>

test:
  <<: *default
  url: postgres://postgres@127.0.0.1:5432
  database: x_tracker_test
  password: <%= ENV.fetch("X_TRACKER_DATABASE_PASSWORD", 'postgres') %>

production:
  <<: *default
  database: x_tracker_production
  username: x_tracker
  password: <%= ENV.fetch("X_TRACKER_DATABASE_PASSWORD", 'postgres') %>
